version: "3.9"
services: 
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "8082:8082"
    links:
      - postgres
    volumes:
      - .:/home/project
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pythonapp
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    networks:
      - python-network
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pythonapp
    ports:
      - "5432:5432"
    networks:
      - python-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - python-network
  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - postgres
    command: tcp postgres:5432 -t 30s -i 250ms
    networks:
      - python-network
networks:
  python-network:
    driver: bridge