version: "3.9"
services: 
  miapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "8082:8082"
    links:
      - mysql
    volumes:
      - .:/home/project
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    networks:
      - python-network
  mysql:  
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=pythonapp
      - MYSQL_USER=joaquin
      - MYSQL_PASSWORD=123456
    networks:
      - python-network
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - python-network
  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - mysql
    command: tcp mysql:3306 -t 30s -i 250ms
    networks:
      - python-network
networks:
  python-network:
    driver: bridge